apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: "redteam-3e9d"
    labels:
        app: "redteam-3e9d"
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/configuration-snippet: | 
         rewrite ^(/dashboard)$ $1/ redirect;
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        kubernetes.io/ingress.class: public
spec:
    rules:
        - host: red-teamad68-redteam-3e9d.4c7399bd4b734105b017.eastus.aksapp.io
          http:
            paths:
            - path: /
              backend:
                serviceName: "redteam-3e9d"
                servicePort: 80
